### PR TITLE
Add working dynamic example

### PR DESCRIPTION
**Pull request by tomjaguarpaw**

### CODE REVIEW

**Comment by tbidne** [comment]
Thanks @tomjaguarpaw! The new [docs](https://discourse.haskell.org/t/bluefin-compared-to-effectful-video/10723/25?u=tbidne) are terrific. Since you have addressed and documented one of my primary questions, I will abuse this opportunity to mention another: is `unsafeRemoveEff` the expected way to implement static interpreters? For instance:

```haskell
runEnvironmentIO ::
  forall envEff es r.
  (envEff :> es) =>
  IOE envEff ->
  (forall e. Environment e -> Eff (e :& es) r) ->
  Eff es r
runEnvironmentIO ioe k = unsafeRemoveEff (k $ MkEnvironment ioe)
```

I ask because while I saw it in the source -- e.g. `Reader` and `State` implementations -- I didn't see it explicitly mentioned in the docs, and the function itself has no documentation (with a scary name :slightly_smiling_face:).

Also, I guess depending on `bluefin-internal` is pretty normal at the moment, at least if you have any intention of defining your own effects (`inContext` and `unsafeRemoveEff` do not seem to be exported from `bluefin`)? I understand the API is probably pretty in-flux while usage crystallizes, so maybe most of the common functionality will be eventually be exported from `bluefin`. Just wanted to check I wasn't missing something.

**Comment by tomjaguarpaw** [comment]
> I will abuse this opportunity to mention another

Yes, please do.

> is `unsafeRemoveEff` the expected way to implement static interpreters?

No, definitely not! You should implement it like the below, following `runCounter4` in the [Wrap multiple effects, don't handle them all](https://hackage.haskell.org/package/bluefin-0.0.4.2/docs/Bluefin-Compound.html#g:5) section of the `Bluefin.Compound` documentation. There's probably a way I can alter the documentation to make this more obvious, but I'm not sure what. If you have an idea please let me know.

```.hs
{-# LANGUAGE GHC2021 #-}

import Bluefin.Eff
import Bluefin.IO
import Bluefin.Compound

newtype Environment e = MkEnvironment (IOE e)

runEnvironmentIO ::
  forall envEff es r.
  (envEff :> es) =>
  IOE envEff ->
  (forall e. Environment e -> Eff (e :& es) r) ->
  Eff es r
runEnvironmentIO ioe k = useImplIn k (MkEnvironment (mapHandle ioe))
```

> I ask because while I saw it in the source -- e.g. `Reader` and `State` implementations

Oh yeah, `unsafeRemoveEff` shouldn't be used there. I fixed it:

* https://github.com/tomjaguarpaw/bluefin/commit/afb396adea5099036d5e3abb2cbeffa278ea5ac1
* https://github.com/tomjaguarpaw/bluefin/commit/e6b63a2f7b6b27f420290ddf1f9610c71adca9b3
* https://github.com/tomjaguarpaw/bluefin/commit/4d51c6f3ff53bcb2134c139b9f1500ea6659774d

> I guess depending on `bluefin-internal` is pretty normal at the moment

It shouldn't be normal, but sometimes you might have to use it as an escape hatch.

> `inContext` and `unsafeRemoveEff` do not seem to be exported from bluefin

I think given the update in `bluefin-0.0.11.0` you should not have to use `inContext` any more. I'm pretty sure `unsafeRemoveEff` has never been needed.

> I understand the API is probably pretty in-flux while usage crystallizes, so maybe most of the common functionality will be eventually be exported from bluefin.

Yeah, that's right, but if you find yourself using something from `bluefin-internal` a lot please [open an issue](https://github.com/tomjaguarpaw/bluefin/issues/new) so that I can advise what best to do.

**Comment by tbidne** [comment]
> > is `unsafeRemoveEff` the expected way to implement static interpreters?
> 
> No, definitely not! You should implement it like the below, following `runCounter4` in the [Wrap multiple effects, don't handle them all](https://hackage.haskell.org/package/bluefin-0.0.4.2/docs/Bluefin-Compound.html#g:5) section of the `Bluefin.Compound` documentation. There's probably a way I can alter the documentation to make this more obvious, but I'm not sure what. If you have an idea please let me know.
> 
> ```haskell
> {-# LANGUAGE GHC2021 #-}
> 
> import Bluefin.Eff
> import Bluefin.IO
> import Bluefin.Compound
> 
> newtype Environment e = MkEnvironment (IOE e)
> 
> runEnvironmentIO ::
>   forall envEff es r.
>   (envEff :> es) =>
>   IOE envEff ->
>   (forall e. Environment e -> Eff (e :& es) r) ->
>   Eff es r
> runEnvironmentIO ioe k = useImplIn k (MkEnvironment (mapHandle ioe))
> ```

Aha! More context on why I was mislead:

1. I missed the bit about `mapHandle` (and `Handle` in general), so I instead tried `useImplIn k (MkEnvironment ioe)`, which doesn't typecheck. I see that `Handle` is mentioned extensively in the [Bluefin.Compound](https://hackage.haskell.org/package/bluefin-0.0.4.2/docs/Bluefin-Compound.html) docs. I think I skipped over it because, to me, wrapping some `IO` operations in a custom `Environment` effect didn't feel like it would be related to "multiple effects", which is what I thought the docs implied.

    Also, the one example in `Bluefin.Compound` involving `IOE` (`runFileSystemIO`) doesn't appear to use `mapHandle`, perhaps because it is dynamic? A simple, static example involving `IOE` might be useful e.g.
    
    ```haskell
    type Terminal :: Effects -> Type
    newtype Terminal e = MkTerminal (IOE e)
    
    putStrLn :: (e :> es) => Terminal e -> String -> Eff es ()
    putStrLn (MkTerminal ioe) = effIO ioe . Prelude.putStrLn
    
    runTerminal ::
      forall termEff es r.
      (termEff :> es) =>
      IOE termEff ->
      (forall e. Terminal e -> Eff (e :& es) r) ->
      Eff es r
    runTerminal ioe k = useImplIn k (MkTerminal (mapHandle ioe))
    ```

2. In `effectful`, the expected way to implement static effects [_is_](https://hackage.haskell.org/package/effectful-2.5.0.0/docs/Effectful-Environment.html#v:getArgs) with a similarly named function:

    ```haskell
    -- unsafeEff_ :: IO a -> Eff es a
    getArgs :: (Environment :> [es]) => Eff [es] [String]
    getArgs = unsafeEff_ E.getArgs
    ```
    
    So when my first attempt didn't typecheck, I found `unsafeRemoveEff` and figured maybe it had a similar purpose. Glad to have that clarified. Perhaps some haddock like, "These aren't the droids you're looking for", wouldn't go amiss?

**Comment by tomjaguarpaw** [comment]
> A simple, static example involving `IOE` might be useful

Sure, I added [Wrap a single effect, don't handle it](https://hackage.haskell.org/package/bluefin-0.0.12.0/docs/Bluefin-Compound.html#g:5) to `Bluefin.Compound` and I [added your terminal example to `bluefin-examples`](https://github.com/tomjaguarpaw/bluefin/blob/master/bluefin-examples/src/Bluefin/Examples/Terminal.hs).

> Perhaps some haddock like, "These aren't the droids you're looking for", wouldn't go amiss?

OK, how about this: https://hackage.haskell.org/package/bluefin-internal-0.0.12.0/docs/Bluefin-Internal.html#v:unsafeRemoveEff

**Comment by tbidne** [comment]
Looks great, thanks!

**Pull request merged**
